# Generated by Django 4.2.5 on 2023-09-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0002_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(choices=[('GUM', 'Гум'), ('SLAVUTINY', 'Славутины'), ('SALON', 'Салон')], default='GUM', max_length=15)),
                ('products', models.ManyToManyField(to='tab.product')),
            ],
        ),
    ]
