# Generated by Django 4.2.5 on 2023-09-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0003_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ManyToManyField(to='tab.seller'),
        ),
    ]
