# Generated by Django 4.2.5 on 2023-09-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(choices=[('GUM', 'Гум'), ('SLAVUTINY', 'Славутины'), ('SALON', 'Салон')], default='Гум', max_length=10),
        ),
    ]
