# Generated by Django 4.2.5 on 2023-09-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0007_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.CharField(choices=[('GUM', 'Гум'), ('SLAVUTINY', 'Славутины'), ('SALON', 'Салон')], default='GUM', max_length=10),
        ),
    ]
