# Generated by Django 4.2.5 on 2023-09-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0008_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='structure',
            field=models.CharField(blank=True, default='-', max_length=20),
        ),
    ]
