# Generated by Django 4.2.5 on 2023-10-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0012_deliveries_remove_product_date_product_date_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='comment',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
